from fastapi import APIRouter, Depends, HTTPException, status, UploadFile, File, Form, BackgroundTasks
from typing import Dict, Any, Optional
import os
import shutil

from app.models.domain_models import JobStatus, DocumentIngestRequest
from app.models.api_models import IngestStatusResponse
from app.api.dependencies import get_config
from app.core.config import AppConfig
from app.engine.ingestion.pipeline import IngestionPipelineManager
from uuid import uuid4

router = APIRouter(prefix="/admin", tags=["Admin & Ingestion"])

@router.post("/ingest", response_model=IngestStatusResponse)
async def start_ingestion(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
    tenant_id: str = Form("default"),
    collection_id: str = Form("default"),
    extraction_mode: str = Form("local_markdown"),
    embedding_mode: str = Form("local_fastembed"),
    config: AppConfig = Depends(get_config)
):
    """
    User uploads a PDF/Image for ingestion along with configuration modes.
    System saves the file and immediately begins processing locally without waiting for API triggers.
    """
    # 1. Ensure upload directory exists
    upload_dir = os.path.join(config.data_dir, "uploads")
    os.makedirs(upload_dir, exist_ok=True)
    
    # 2. Save the incoming binary file to local disk
    safe_filename = file.filename or "unknown_upload.bin"
    file_path = os.path.join(upload_dir, f"{uuid4().hex}_{safe_filename}")
    
    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
        
    # 3. Create the ingest request model (including bypassing config)
    request_data = DocumentIngestRequest(
        source_path=file_path,
        filename=safe_filename,
        content_type=file.content_type or "application/octet-stream",
        tenant_id=tenant_id,
        collection_id=collection_id,
        extraction_mode=extraction_mode,
        embedding_mode=embedding_mode
    )
    
    # 4. Save job to SQLite state machine
    manager = IngestionPipelineManager()
    job = manager.create_job(request=request_data)
    
    # 5. Immediately dispatch the parsing stage in the background
    background_tasks.add_task(manager.execute_parsing_stage, job.job_id)
    
    return IngestStatusResponse(
        job_id=job.job_id,
        status=JobStatus.PROCESSING,
        message="File uploaded successfully. Processing will continue seamlessly in the background."
    )

@router.get("/ingest/{job_id}/status", response_model=IngestStatusResponse)
async def get_job_status(job_id: str):
    """
    Check the current status of an ingestion job from the SQLite state machine.
    """
    from app.storage.relations_db import get_connection
    
    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(
            "SELECT job_id, status, error FROM ingestion_jobs WHERE job_id = ?",
            (job_id,)
        )
        row = cursor.fetchone()
    
    if not row:
        raise HTTPException(status_code=404, detail=f"Job '{job_id}' not found.")
    
    status_value = row["status"]
    error_msg = row["error"]
    
    # Map status to a human-readable message
    messages = {
        "queued": "Job is queued and waiting to be picked up.",
        "processing": "Job is currently being parsed and chunked.",
        "embedding_and_indexing": "Chunks are ready — waiting for embedding scheduler.",
        "complete": "Document successfully processed and vectors embedded!",
        "failed": f"Job failed: {error_msg or 'Unknown error'}",
    }
    
    try:
        job_status = JobStatus(status_value)
    except ValueError:
        # Handle any legacy statuses (e.g. 'waiting_vpn_off') gracefully
        job_status = JobStatus.FAILED
        return IngestStatusResponse(
            job_id=job_id,
            status=job_status,
            message=f"Job has a legacy status '{status_value}' — please re-upload."
        )
    
    return IngestStatusResponse(
        job_id=job_id,
        status=job_status,
        message=messages.get(status_value, f"Status: {status_value}")
    )

@router.get("/debug/vectors")
async def view_qdrant_vectors(limit: int = 1):
    """
    DEBUG: See the actual mathematical sequences generated by fastembed!
    """
    from app.storage.vector_db import get_qdrant_client
    qdrant = get_qdrant_client()
    try:
        # Scroll returns a tuple (records, next_page_offset)
        records, _ = qdrant.scroll(
            collection_name="rag_text", 
            limit=limit, 
            with_vectors=True
        )
        
        if not records:
            return {"message": "No vectors found. Make sure you fully complete an upload and VPN ingestion flow first!"}
            
        results = []
        for record in records:
            # We crop the array to 10 numbers so we don't crash the browser rendering 384 or 1536 floats
            vec_preview = record.vector[:10] if record.vector else []
            dim_size = len(record.vector) if record.vector else 0
            
            results.append({
                "point_id": record.id,
                "payload": record.payload,
                "dimension_size": dim_size,
                "sequence_preview": vec_preview
            })
            
        return {"vectors": results}
    except Exception as e:
        return {"error": str(e)}


@router.delete("/debug/purge-vectors", summary="Wipe all vectors from Qdrant and reset job history")
async def purge_all_vectors():
    """
    DEBUG: Deletes and recreates the Qdrant collection, removing ALL indexed vectors.
    Also marks all SQLite ingestion jobs as purged so they don't block re-ingestion.
    Use this to clear stale mock/test data before uploading real documents.
    """
    from app.storage.vector_db import get_qdrant_client, COLLECTION_NAME, ensure_collection
    import app.storage.vector_db as _vdb
    from app.storage.relations_db import get_connection

    qdrant = get_qdrant_client()
    deleted_count = 0

    try:
        info = qdrant.get_collection(COLLECTION_NAME)
        deleted_count = info.points_count or 0
    except Exception:
        pass

    try:
        qdrant.delete_collection(COLLECTION_NAME)
        # Recreate using the SAME client — do NOT open a second concurrent client
        ensure_collection(qdrant)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to purge Qdrant collection: {e}")

    # Also clean up SQLite job records so status tracking doesn't show stale state
    with get_connection() as conn:
        cursor = conn.cursor()
        cursor.execute("DELETE FROM ingestion_jobs")
        conn.commit()

    return {
        "message": f"Purged {deleted_count} vectors from collection '{COLLECTION_NAME}' and cleared all job records. Re-upload your documents.",
        "vectors_deleted": deleted_count
    }
